#!/usr/bin/env bash

set -eo pipefail

APP_NAME="${1}"
MODULE_NAME="${2}"

FIND_APP_NAME="hello"
FIND_MODULE_NAME="Hello"
FIND_FRAMEWORK="django"

if [ -z "${APP_NAME}" ] || [ -z "${MODULE_NAME}" ]; then
    echo "You must supply both an app and module name, example: ${0} myapp MyApp"
    exit 1
fi

cat << EOF
Are you happy with the name you've picked for your app?

Just asking because running this script is a 1 way action,
once things have been renamed this script will no longer work.

You would have to clone down the repo again to pick a new name.

EOF

while true; do
    read -p "Continue with ${APP_NAME} / ${MODULE_NAME} (y/n)? " -r yn
    case "${yn}" in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "";;
    esac
done

# ------------------------------------------------------------------
# This is the core of the script which renames a few things.
# ------------------------------------------------------------------
find . -type f -exec \
  perl -i -pe "s/(${FIND_APP_NAME}${FIND_FRAMEWORK}|${FIND_APP_NAME})/${APP_NAME}/g" {} + \
  && find . -type f -exec \
    perl -i -pe "s/${FIND_MODULE_NAME}/${MODULE_NAME}/g" {} +
# ------------------------------------------------------------------

cat << EOF

--------------------------------------------------------------------
Your project has been renamed successfully!
--------------------------------------------------------------------

EOF

function init_git_repo {
  [ ! -d .git/ ] && return 0

  rm -rf .git/

cat << EOF

--------------------------------------------------------------------
$(git init)
--------------------------------------------------------------------
EOF

  git symbolic-ref HEAD refs/heads/main
}

while true; do
    read -p "Do you want to init a new local git repo (y/n)? " -r yn
    case "${yn}" in
        [Yy]* ) init_git_repo; break;;
        [Nn]* ) break;;
        * ) echo "";;
    esac
done

cat << EOF

We're done here. You can delete this script by running: rm customize

Check out the rest of the README on GitHub to wrap things up.
EOF
